---

- hosts: all
  become: True

  tasks:

    - name: Create a temp directory
      tempfile:
        state: directory
        prefix: snake
      register: tempfile_result

    - name: Download and unarchive the Snake-Server binary
      unarchive:
        src: "{{ snake_archive_url }}"
        dest: "{{ tempfile_result.path }}"
        remote_src: yes
        list_files: yes
      register: unarchive_result

    - name: Stop the Snake-Server's systemd service
      service:
        name: "{{ snake_systemd_service_name }}"
        state: stopped

    - name: Copy new a binary
      command: "cp {{ tempfile_result.path }}/{{ unarchive_result.files | first }} {{ snake_install_path }}/{{ snake_binary_name }}"

    - name: Check the binary of the Snake-Server
      file:
        name: "{{ snake_install_path }}/{{ snake_binary_name }}"
        state: file
        mode: 0755

    - name: Enable and start the Snake-Server
      service:
        name: "{{ snake_systemd_service_name }}"
        state: restarted
        enabled: yes
